/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/room/model.glb 
*/

import React, { useEffect} from 'react'
import { useGLTF } from '@react-three/drei'
import { motion } from "framer-motion-3d";
import { MotionConfig } from 'framer-motion';
import { framerMotionConfig } from '../config';

export function Room(props) {
  const{section}=props;
  const { nodes, materials } = useGLTF('/models/room/model.glb')
  useEffect(()=>{ console.log(section)},[section])
  return (
    <MotionConfig
        transition={{
          ...framerMotionConfig,
        }}
      >

    <motion.group {...props} dispose={null} scale={[0, 0, 0]}
    animate={{
      scale: section === 0 ? 1 : 0,
    }}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} position={[-1.367, 1.234, 0.096]} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material} position={[-1.367, 1.234, 0.096]} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-1.367, -0.2, -1.234]} />
    </motion.group>
      </MotionConfig>
  )
}

useGLTF.preload('/models/room/model.glb')
